# core/protocol.py

"""US4x4 communication protocol"""

COMMAND_POWERSAVE = 0x03
COMMAND_INPUT_ENABLE = 0x05
COMMAND_MONITORING_MODE = 0x07
COMMAND_ROUTING = 0x09

INDICES_POWERSAVE = [0]
INDICES_INPUT_ENABLE = [0, 1, 2, 3]
INDICES_MONITORING_MODE = [0, 1]
INDICES_ROUTING = [0, 1]